# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 05:23
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_svg', '0002_auto_20160705_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filersvg',
            name='image',
            field=filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
        ),
    ]
