# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-16 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_svg', '0005_auto_20170131_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='filersvg',
            name='image_classes',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CSS classes'),
        ),
    ]
